# Generated by Django 5.2.7 on 2025-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kyc',
            field=models.ImageField(choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], upload_to='kyc_documents/'),
        ),
    ]
