# Generated by Django 5.2.7 on 2025-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_customer_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kyc_type',
            field=models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], default='Aadhaar', max_length=20),
        ),
    ]
