# Generated by Django 5.2.7 on 2025-10-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_customer_kyc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
