# Generated by Django 5.2.7 on 2025-10-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_customer_kyc_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kyc',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
